function createfigure(YMatrix1, YMatrix2, YMatrix3, YMatrix4, YMatrix5, YMatrix6, YMatrix7, YMatrix8, YMatrix9, YMatrix10, YMatrix11, YMatrix12)
%CREATEFIGURE(YMATRIX1,YMATRIX2,YMATRIX3,YMATRIX4,YMATRIX5,YMATRIX6,YMATRIX7,YMATRIX8,YMATRIX9,YMATRIX10,YMATRIX11,YMATRIX12)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data
%  YMATRIX5:  matrix of y data
%  YMATRIX6:  matrix of y data
%  YMATRIX7:  matrix of y data
%  YMATRIX8:  matrix of y data
%  YMATRIX9:  matrix of y data
%  YMATRIX10:  matrix of y data
%  YMATRIX11:  matrix of y data
%  YMATRIX12:  matrix of y data

%  Auto-generated by MATLAB on 15-Mar-2011 10:50:55

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,4,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1);
set(plot1(1),'Color',[0 0 0]);
set(plot1(2),'Color',[0 0 1]);
set(plot1(3),'Color',[0 1 0]);
set(plot1(4),'Color',[0 1 1]);

% Create title
title('Top plane U component comparison');

% Create subplot
subplot2 = subplot(3,4,5,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',subplot2);
set(plot2(1),'Color',[0 0 0]);
set(plot2(2),'Color',[0 0 1]);
set(plot2(3),'Color',[0 1 0]);
set(plot2(4),'Color',[0 1 1]);

% Create title
title('Top plane V component comparison');

% Create subplot
subplot3 = subplot(3,4,9,'Parent',figure1);
box(subplot3,'on');
hold(subplot3,'all');

% Create multiple lines using matrix input to plot
plot3 = plot(YMatrix3,'Parent',subplot3);
set(plot3(1),'Color',[0 0 0]);
set(plot3(2),'Color',[0 0 1]);
set(plot3(3),'Color',[0 1 0]);
set(plot3(4),'Color',[0 1 1]);

% Create title
title('Top plane W component comparison');

% Create subplot
subplot4 = subplot(3,4,2,'Parent',figure1);
box(subplot4,'on');
hold(subplot4,'all');

% Create multiple lines using matrix input to plot
plot4 = plot(YMatrix4,'Parent',subplot4);
set(plot4(1),'Color',[1 0 0]);
set(plot4(2),'Color',[1 0 1]);
set(plot4(3),'Color',[1 1 0]);
set(plot4(4),'Color',[0.5 0.5 0.5]);

% Create title
title('Bottom plane U component comparison');

% Create subplot
subplot5 = subplot(3,4,6,'Parent',figure1);
box(subplot5,'on');
hold(subplot5,'all');

% Create multiple lines using matrix input to plot
plot5 = plot(YMatrix5,'Parent',subplot5);
set(plot5(1),'Color',[1 0 0]);
set(plot5(2),'Color',[1 0 1]);
set(plot5(3),'Color',[1 1 0]);
set(plot5(4),'Color',[0.5 0.5 0.5]);

% Create title
title('Bottom plane V component comparison');

% Create subplot
subplot6 = subplot(3,4,10,'Parent',figure1);
box(subplot6,'on');
hold(subplot6,'all');

% Create multiple lines using matrix input to plot
plot6 = plot(YMatrix6,'Parent',subplot6);
set(plot6(1),'Color',[1 0 0]);
set(plot6(2),'Color',[1 0 1]);
set(plot6(3),'Color',[1 1 0]);
set(plot6(4),'Color',[0.5 0.5 0.5]);

% Create title
title('Bottom plane W component comparison');

% Create subplot
subplot7 = subplot(3,4,3,'Parent',figure1);
box(subplot7,'on');
hold(subplot7,'all');

% Create multiple lines using matrix input to plot
plot7 = plot(YMatrix7,'Parent',subplot7);
set(plot7(1),'Color',[0 1 0]);
set(plot7(2),'Color',[0 1 1]);
set(plot7(3),'Color',[1 1 0]);
set(plot7(4),'Color',[0.5 0.5 0.5]);

% Create title
title('Front plane U component comparison');

% Create subplot
subplot8 = subplot(3,4,7,'Parent',figure1);
box(subplot8,'on');
hold(subplot8,'all');

% Create multiple lines using matrix input to plot
plot8 = plot(YMatrix8,'Parent',subplot8);
set(plot8(1),'Color',[0 1 0]);
set(plot8(2),'Color',[0 1 1]);
set(plot8(3),'Color',[1 1 0]);
set(plot8(4),'Color',[0.5 0.5 0.5]);

% Create title
title('Front plane V component comparison');

% Create subplot
subplot9 = subplot(3,4,11,'Parent',figure1);
box(subplot9,'on');
hold(subplot9,'all');

% Create multiple lines using matrix input to plot
plot9 = plot(YMatrix9,'Parent',subplot9);
set(plot9(1),'Color',[0 1 0]);
set(plot9(2),'Color',[0 1 1]);
set(plot9(3),'Color',[1 1 0]);
set(plot9(4),'Color',[0.5 0.5 0.5]);

% Create title
title('Front plane W component comparison');

% Create subplot
subplot10 = subplot(3,4,4,'Parent',figure1);
box(subplot10,'on');
hold(subplot10,'all');

% Create multiple lines using matrix input to plot
plot10 = plot(YMatrix10,'Parent',subplot10);
set(plot10(1),'Color',[0 0 0]);
set(plot10(2),'Color',[0 0 1]);
set(plot10(3),'Color',[1 0 1]);
set(plot10(4),'Color',[1 0 0]);

% Create title
title('Rear plane U component comparison');

% Create subplot
subplot11 = subplot(3,4,8,'Parent',figure1);
box(subplot11,'on');
hold(subplot11,'all');

% Create multiple lines using matrix input to plot
plot11 = plot(YMatrix11,'Parent',subplot11);
set(plot11(1),'Color',[0 0 0]);
set(plot11(2),'Color',[0 0 1]);
set(plot11(3),'Color',[1 0 1]);
set(plot11(4),'Color',[1 0 0]);

% Create title
title('Rear plane V component comparison');

% Create subplot
subplot12 = subplot(3,4,12,'Parent',figure1);
box(subplot12,'on');
hold(subplot12,'all');

% Create multiple lines using matrix input to plot
plot12 = plot(YMatrix12,'Parent',subplot12);
set(plot12(1),'Color',[0 0 0]);
set(plot12(2),'Color',[0 0 1]);
set(plot12(3),'Color',[1 0 1]);
set(plot12(4),'Color',[1 0 0]);

% Create title
title('Rear plane W component comparison');

